" .vimrc file
" Vladimir 'dvn' Dranyonkov, 2013-08-13

set nocompatible
filetype plugin on
syntax on
colorscheme dgrin

set vb t_vb=
set backspace=indent,eol,start

set shiftwidth=2
set tabstop=2
set smarttab

set foldenable
set foldmethod=syntax

set autoindent
set cindent

set showmatch

set nu
set cursorline
set colorcolumn=100
set scrolloff=5

set ignorecase

" Status line
set laststatus=2

" QuickFix and Make
set switchbuf=useopen,usetab,newtab

" Man pages
runtime! ftplugin/man.vim
nmap K :Man 3 <cword><CR>
