" .vimrc file
" Vladimir Dranyonkov, 2013-08-13

set nocompatible
filetype plugin on
syntax on

set vb t_vb=
set backspace=indent,eol,start

set shiftwidth=2
set tabstop=2
set smarttab

set foldenable
set foldmethod=syntax

set autoindent
set cindent

set showmatch

set nu
set cursorline
set scrolloff=5

set ignorecase

" Status line
set laststatus=2

" QuickFix and Make
set switchbuf=useopen,usetab,newtab
