" .vimrc file
" Vladimir Dranyonkov, 2013-08-13

set nocompatible
filetype plugin on
syntax on
colorscheme dgrin

set vb t_vb=
set backspace=indent,eol,start

set shiftwidth=2
set tabstop=2
set smarttab

set foldenable
set foldmethod=syntax

set autoindent
set cindent

set showmatch

set nu
set cursorline
set scrolloff=5

set ignorecase

" Status line
set laststatus=2

" QuickFix and Make
set switchbuf=useopen,usetab,newtab

" Autocomplete
set pumheight=15

" Clang complete
let g:clang_auto_select=1
let g:clang_close_preview=1
let g:clang_user_options='-std=c++11'
let g:clang_trailing_placeholder=1
let g:clang_complete_macros=1
let g:clang_complete_patterns=1
let g:clang_periodic_quickfix=1
let g:clang_complete_copen=1
